-- 1. Create the palettes table
create table palettes (
  id bigint generated by default as identity primary key,
  colors text[] not null,
  likes integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tag text not null
);

-- 2. Insert some initial dummy data just to test it
insert into palettes (colors, likes, tag) values
  ('{"#03045e", "#0077b6", "#00b4d8", "#90e0ef"}', 1845, 'Cold'),
  ('{"#ff595e", "#ffca3a", "#8ac926", "#1982c4"}', 1250, 'Warm'),
  ('{"#ccd5ae", "#e9edc9", "#fefaec", "#d4a373"}', 934, 'Vintage'),
  ('{"#2b2d42", "#8d99ae", "#edf2f4", "#ef233c"}', 2100, 'Dark'),
  ('{"#cdb4db", "#ffc8dd", "#ffafcc", "#bde0fe"}', 3240, 'Pastel'),
  ('{"#14213d", "#fca311", "#e5e5e5", "#ffffff"}', 1450, 'Dark');
